language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm

sudo: false

matrix:
  include:
    - php: 7.1
      env:
        - ENVIRONMENT="coverage"

before_script:
  - travis_retry composer self-update
  - travis_retry composer install

script:
  - vendor/bin/phpcs  -p --standard=PSR2 --runtime-set ignore_errors_on_exit 1 --runtime-set ignore_warnings_on_exit 1 src/
  - vendor/bin/phpunit --coverage-clover=coverage.clover

after_script:
  - if [ "$ENVIRONMENT" == 'coverage' ]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover;  fi